### ISSUE TITLE
use fillable pdf as template

### ISSUE THREAD

**Issue by herbie4** [GravityPDF/gravity-pdf#1057]
Great plugin! Just wondering if there is a way to use a fillable pdf as template and set some field values on generation of pdf.

**Comment by jakejackson1** [comment]
While mPDF does have some capabilities for using an existing PDF, all fillable form fields are automatically stripped out of the document during this process. Best look at an alternative solution like [For Gravity Fillable PDFs](https://forgravity.com/plugins/fillable-pdfs/) instead.
