### ISSUE TITLE
How to avoid attaching PDF

### ISSUE THREAD

**Issue by jasimp** [GravityPDF/gravity-pdf#1075]
hello
I am looking for a solution to avoid PDF as attachment to the notification . Will use short code generated link instead.
can any one help me to work out this?

thank you

**Comment by jakejackson1** [comment]
Hi there,

GitHub is for developers to report bugs and discuss new features. For support, [please use our online support form](https://gravitypdf.com/support/#contact-support) and one of the team will be happy to assist.
