### ISSUE TITLE
GF 2.5 Entry details Metabox : Empty pdf list

### ISSUE THREAD

**Issue by jestonihpi** [GravityPDF/gravity-pdf#1080]
![image](https://user-images.githubusercontent.com/434866/87731265-a4df3900-c7fc-11ea-898d-7f2c4d75cc50.png)

How to handle this?

First option:
Remove the metabox if there were no pdf template found.

Second option:
Provide a text message examples:
![image](https://user-images.githubusercontent.com/434866/87731523-44043080-c7fd-11ea-887b-cf46e04da34f.png)
 or
![image](https://user-images.githubusercontent.com/434866/87731706-b248f300-c7fd-11ea-8aea-f86e0c8d83c0.png)

**Comment by jakejackson1** [comment]
@jestonihpi after considering our options here, I'd like to:

1. If there's active zero PDFs configured on the Gravity Form we'll remove the PDF meta box altogether.
2. If there're PDFs configured BUT the conditional logic assigned to those PDFs means the current entry doesn't have any active, then we'll include the meta box and display a message about the entry having no PDFs available. 
3. Normal behaviour if the entry has PDF(s) for display.

**Comment by jestonihpi** [comment]
@jakejackson1 , Copy. Thanks!
