### ISSUE TITLE
How can I view the generated markup before converting to PDF?

### ISSUE THREAD

**Issue by JacobDB** [GravityPDF/gravity-pdf#1105]
To make development easier, I'd like to view the page that is used to generate a PDF. This will make it easier to identify how to target elements by being able to directly Inspect Element on each item. Is this something that is possible to achieve?

**Comment by JacobDB** [comment]
Never mind, hunted through the source code and deciphered that `?html=true` will output the raw HTML. Might want to put something about that in the docs (maybe I just missed it).

**Comment by jakejackson1** [comment]
Glad you found what you were looking for! Also https://gravitypdf.com/documentation/v5/development-helper-parameters/
