### ISSUE TITLE
CSS Ready Classes Broken

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#1139]
Forms using CSS Ready Classes for columns don't function correctly in 6.0.

**Comment by jestonihpi** [comment]
Notes:
This is part of GF 2.5 legacy class conversion.

![image](https://user-images.githubusercontent.com/434866/110567062-dfcb1e00-818b-11eb-865a-1ed5ea2e7d32.png)
![image](https://user-images.githubusercontent.com/434866/110567092-ece80d00-818b-11eb-8162-0ed1d8734fc6.png)

![image](https://user-images.githubusercontent.com/434866/110567109-f3768480-818b-11eb-8716-36d20bbe5b3e.png)
