### ISSUE TITLE
Multiple Font Name displays on Font Settings

### ISSUE THREAD

**Issue by ayenmot** [GravityPDF/gravity-pdf#1151]
Duplicate Font Name displays on Font Settings when PACKAGED template installed multiple times.

**Comment by jakejackson1** [comment]
@ayenmot since this issue is only relevant to Gravity PDF 6.0, you should specifically say that in the issue. Extra info such as screenshots are also helpful, and adding the correct Labels/Milestone to the issue saves a bunch of organising.
