### ISSUE TITLE
Not passing <select> size attribute if < 2

### ISSUE THREAD

**Issue by sornman** [GravityPDF/gravity-pdf#1185]
When attempting to display a PDF select field, you can set the size attribute (default is 1). However, that information is not being passed to the mpdf $objattr array, so it doesn't get passed to print_ob_select() in Form.php (line 349). If you set size="2" or greater, the value is passed.

I have created an issue (https://github.com/mpdf/mpdf/issues/1369) to fix this issue, but it would be nice to have the fix pulled into the vendor/mpdf branch of gravity-pdf.

**Comment by jakejackson1** [comment]
Thanks for opening the issue. When a Pull Request is created and merged into mPDF for this problem, it'll get automatically merged into Gravity PDF when we bump the mPDF version in composer (we do this on minor releases unless there is a breaking change). Going to close for now as it's an upstream problem.
