### ISSUE TITLE
System Status: Logged Out Timeout Empty

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#1188]
**Description**
On the System Status, the Logged Out Timeout value only shows the string `minutes`, without the actual number of minutes that applies. 

**Step To Reproduce**
1. Run the PDF Uninstaller
1. Activate Gravity PDF
1. Go to Forms -> System Status
2. View the Logged Out Timeout value

**Expected behavior**
To show the default number of minutes: 20

**Screenshots**
![Screen Shot 2021-03-01 at 11 05 59 am](https://user-images.githubusercontent.com/2918419/109438452-2cbd3f00-7a7e-11eb-8341-53be2577b7cb.png)

**Additional context**
Because the Forms -> Settings -> PDF globals haven't been saved, a value for `logged_out_timeout` doesn't exist, and it should fallback to the default (`20`).

**Comment by jestonihpi** [comment]
Related to #1199
