### ISSUE TITLE
Move Gravity PDF Uninstaller to Settings -> Uninstall

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#1191]
**Description**
Gravity Forms has moved all their add-on uninstaller under Settings -> Uninstall. We should do the same

**Step To Reproduce**
1. Go to Settings -> Uninstall with a Gravity Forms add-on enabled

**Expected behavior**
Show Gravity PDF on this list

**Screenshots**
<img width="936" alt="Screen Shot 2021-03-01 at 11 28 20 am" src="https://user-images.githubusercontent.com/2918419/109439134-401dd980-7a81-11eb-9c53-c17b6d36903f.png">

**Comment by jakejackson1** [comment]
@jestonihpi I've completed the bulk of this work, but it'll need a thorough review and testing to verify nothing is amiss.

**Comment by jestonihpi** [comment]
@jakejackson1 , I've tested and checked this update, the uninstall functionality doesnt work on my end.

![image](https://user-images.githubusercontent.com/434866/110874481-c30b2380-830e-11eb-8b71-5ddf1b96eb21.png)

After refresh:

![image](https://user-images.githubusercontent.com/434866/110874504-cbfbf500-830e-11eb-8ab2-25e8f807ce23.png)

**Comment by jakejackson1** [comment]
Can you Xdebug it on the `Controller_Uninstaller::uninstall_addon()` method please and see what's going on?

**Comment by jestonihpi** [comment]
On it @jakejackson1 .

**Comment by jestonihpi** [comment]
Update @jakejackson1, its now working on my end. Thanks!

**Comment by jakejackson1** [comment]
@jestonihpi woohoo! What was wrong?
