### ISSUE TITLE
Copy System Status - Message out of place.

### ISSUE THREAD

**Issue by jestonihpi** [GravityPDF/gravity-pdf#1198]
**Description**
The UI for the confirmation when you copy-to-clipboard the system status is out place.

**Step To Reproduce**
1. Go to 'System Status'
2. Click on 'Copy System Report'
3. Success message shows.

**Expected behavior**
It should align to the Copy System Report UI

**Screenshots**
![image](https://user-images.githubusercontent.com/434866/109456569-fe078000-7a0d-11eb-9e91-12cbb032ba79.png)

**Comment by jakejackson1** [comment]
@jestonihpi Does this issue occur when Gravity PDF is disabled?

**Comment by jestonihpi** [comment]
Yes @jakejackson1. It seems its on GF side.

**Comment by jakejackson1** [comment]
Copy. Will close as it's not relevant to Gravity PDF directly.
