### ISSUE TITLE
System Status Clipboard copy is missing some data.

### ISSUE THREAD

**Issue by jestonihpi** [GravityPDF/gravity-pdf#1199]
**Description**

**Step To Reproduce**
1. Go to 'System Status'
2. Click on 'Copy System Report'
3. Paste the copied information into a text-editor.
4. See missing information under Global Settings.

**Expected behavior**
It should display the corresponding values on System Status page.

**Screenshots**
![image](https://user-images.githubusercontent.com/434866/109457004-d533ba80-7a0e-11eb-89b6-72c28c9c0407.png)

![image](https://user-images.githubusercontent.com/434866/109457051-ef6d9880-7a0e-11eb-9c6d-39f91bc32d2b.png)

**Comment by jakejackson1** [comment]
@jestonihpi don't forget to mark the milestone as 6.0! Thanks :)

**Comment by jakejackson1** [comment]
Related https://github.com/GravityPDF/gravity-pdf/issues/1188

**Comment by jestonihpi** [comment]
Copy @jakejackson1
