### ISSUE TITLE
Template manager - Update template list sequencing bug

### ISSUE THREAD

**Issue by debbieellis7** [GravityPDF/gravity-pdf#1202]
**Description**
After choosing a new PDF template by selecting one using the select box dropdown, Template manager list won't be updated with correct sequence of template data.

**Step To Reproduce**
1. Select PDF template from select box dropdown
2. Open template manager by clicking the advanced button
3. 
4.

**Expected behavior**
The new selected PDF template should be shown first at the very top of the font manager queue.

**Screenshots**

![1](https://user-images.githubusercontent.com/10412650/110263586-2a189780-7ff2-11eb-83ab-cc939045587e.png)
![2](https://user-images.githubusercontent.com/10412650/110263590-2be25b00-7ff2-11eb-8d48-4536b9c94c5e.png)
![3](https://user-images.githubusercontent.com/10412650/110263594-2c7af180-7ff2-11eb-8172-c887d4f4fdc9.png)

**Additional context**

**Comment by jakejackson1** [comment]
@debbieellis7 you've got to get more descriptive with your GitHub Titles, so we can see at a glance what the issue is. Also, get in the habit of correctly filling out the issue template in detail, and including screenshots is immensely helpful as well.
