### ISSUE TITLE
System Status : Support for multisite template paths.

### ISSUE THREAD

**Issue by jestonihpi** [GravityPDF/gravity-pdf#1229]
**Description**
Currently we are only showing the template path information for single sites.  We should also show the correct paths for multi-site installation as well.

**Step To Reproduce**
1. Set up a multi site WP installation.  (https://www.wpbeginner.com/wp-tutorials/how-to-install-and-setup-wordpress-multisite-network/) 
2. Enable multisite and re activate plugins. ( Gravity Forms and Gravity PDF )
3. Go to Forms -> System Status.
4. See error.

**Expected behavior**
Gravity PDF template path should be suffixed with the network id e.g /wp-content/uploads/PDF_EXTENDED_TEMPLATES/1/

**Screenshots**
Proper path for multisite.
![image](https://user-images.githubusercontent.com/434866/111399368-37bfd280-8700-11eb-8849-12a6fa69986c.png)

**Additional context**
I cant recall if this has been discussed, but I think its worth to look at this.  This is while I was checking on Helper_Data's multisite_template_location_url property when I found this bug.

**Comment by jakejackson1** [comment]
@jestonihpi good catch. We should be using `Helper_Templates::get_template_path()` and `Helper_Templates::get_template_url()` to account for this use case.
