### ISSUE TITLE
Maximise Font Manager Add / Update panel width in RTL mode

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#1240]
**Description**
In RTL Mode, the Font Manager panel on the left side could be wider to maximise the available space

**Step To Reproduce**
1. Adjust Site Language to RTL type (Settings->General->Site Language)
2. Click to PDF List page and add or edit a PDF
3. Scroll down to Appearance section and click the Manage button on the Font selector
4. See available space in the Add / Update font panel

**Expected behavior**
To use the full space available

**Screenshots**
<img width="1156" alt="Screen Shot 2021-03-23 at 8 27 24 am" src="https://user-images.githubusercontent.com/2918419/112066195-a47c1680-8bb1-11eb-8c92-df4f85b00c03.png">

**Comment by debbieellis7** [comment]
Decided to close this issue for now.
