### ISSUE TITLE
PDF List - Download Shortcode 

### ISSUE THREAD

**Issue by jestonihpi** [GravityPDF/gravity-pdf#1246]
**Description**
We need a more intuitive presentation for this boxes.  

**Step To Reproduce**
1. Go to 'Forms -> Create / Select A form'
2. Click on 'PDF '
3. Scroll down to 'PDF List'

**Expected behavior**
We can strip the borders and background so it would stand as a standard input box. 
![image](https://user-images.githubusercontent.com/434866/112401979-a0353200-8d46-11eb-8419-cee9a99f8aac.png)
Optional : Add a message like the system status.
![image](https://user-images.githubusercontent.com/434866/112402661-e6d75c00-8d47-11eb-943d-9105867b35f8.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/434866/112401806-459bd600-8d46-11eb-80f3-672d75257a91.png)

**Comment by jakejackson1** [comment]
@dantabifranca also reported he could not copy the shortcode using Firefox and Safari on Mac.

**Comment by jakejackson1** [comment]
I tested in Safari on Mac and didn't have any issues.

**Comment by jestonihpi** [comment]
Hi @jakejackson1  on this proposals, I've used FA's fa-code class. As for the tooltip, they are just directly replicas with GF's tooltip UI.

Design concept : 
Proposal # 1 :
![image](https://user-images.githubusercontent.com/434866/115488816-ba9ef480-a28d-11eb-8d45-4ca602441a16.png)
Used the Gravity PDF Logo color as background with the tooltip icon floating on it.

Proposal # 2:
![image](https://user-images.githubusercontent.com/434866/115489119-3bf68700-a28e-11eb-84eb-f73f20fa55ca.png)
Follow the color scheme for links and adjusted the tooltip icon next to the short code icon.

Additional Idea :

We can either use window's prompt or create a separate modal for it, in which user can manually select or if the OK button is selected  - the `copy-to-clipboard` script executes.

![image](https://user-images.githubusercontent.com/434866/115489706-377e9e00-a28f-11eb-8980-98d23b6ed267.png)


Let me know what you think.

**Comment by jestonihpi** [comment]
Hi @jakejackson1, here is the initial design via jsfiddle : https://jsfiddle.net/v4Ljqdsf/10/

**Comment by jakejackson1** [comment]
Let's drop the tooltip and have the success message directly in the button itself.

**Comment by jestonihpi** [comment]
Updated prototype @jakejackson1  : https://jsfiddle.net/v4Ljqdsf/21/ thanks!

**Comment by jakejackson1** [comment]
Can the confirmation text be updated to reflect the content that is copied? It's not a report. Also, I'm on my phone so I can't check, but is this fully accessible? Finally, can we have a <noscript> fallback so it shows the <input> field we have now so a user could copy the shortcode manually?

**Comment by jestonihpi** [comment]
Copy @jakejackson1

**Comment by jestonihpi** [comment]
Hi @jakejackson1, this is the revised version of the prototype which contains the noscript fallback and provided two option for the content. Let me know what you think. Thanks!

**Comment by jakejackson1** [comment]
@jestonihpi I've made some improvements https://jsfiddle.net/gravitypdf/t6q9zwmx/1/

But I'd like to be able to do this entire functionality without the clipboard.js library. We also need to handle when the copy to clipboard functionality fails, and we should fallback to showing an error message and the `<input />` box in `noscript` so that the user can manually copy.

Here's what GF does:

```
	const copyToClipboard = (text) => {
		if (window.clipboardData && window.clipboardData.setData) {
			// Internet Explorer-specific code path to prevent textarea being shown while dialog is visible.
			return window.clipboardData.setData("Text", text);

		}
		else if (document.queryCommandSupported && document.queryCommandSupported("copy")) {
			var textarea = document.createElement("textarea");
			textarea.textContent = text;
			textarea.style.position = "fixed";  // Prevent scrolling to bottom of page in Microsoft Edge.
			document.body.appendChild(textarea);
			textarea.select();
			try {
				return document.execCommand("copy");  // Security exception may be thrown by some browsers.
			}
			catch (ex) {
				console.warn("Copy to clipboard failed.", ex);
				return false;
			}
			finally {
				document.body.removeChild(textarea);
			}
		}
	}
```

**Comment by jestonihpi** [comment]
@jakejackson1, yep were going to use the GF script for the copy-to-clipboard function and as for the screen reader requirements - we can match `aria-live` (polite) with `role=status`.

**Comment by jakejackson1** [comment]
@jestonihpi okay, so use it in the JSFiddle and get the appropriate aria stuff added please.

**Comment by jestonihpi** [comment]
Hi @jakejackson1, I have applied the correct aria live and able to make the `copyToClipboard` changes based the requirements.
: https://jsfiddle.net/t0ohc13L/1/

Thanks.

**Comment by jakejackson1** [comment]
@jestonihpi thanks. Let's do the following:

1. Remove `<noscript>`
2. Remove `display:none` on the `<input />`
3. Remove the inline onClick event on the button
4. When the page loads, hide the `<input />` field using JS, add an onClick event to the button, and use the contents of the `<input />` tags `value` as the copied text.

This will remove a bunch of markup we don't need.

You should also find out the correct color Hex codes to use for the button standard and success states and update the CSS please.

**Comment by jestonihpi** [comment]
Hi @jakejackson1, I have updated the prototype here : https://jsfiddle.net/vy94cgdr/1/

Notes: 
Fixed the correct hex for the success message ( copied from gf_copy_success ).
Added dashicon icons for tick and shortcode icons.

Thanks!

**Comment by jakejackson1** [comment]
@jestonihpi much better. 

Couple more items worth looking at:

1. The cursor for the hover state should be a pointer
2. After transforming to the shortcode copied state, you should set a reasonable timeout that will automatically reset the button back to its original state. 
3. The input ID should be something like `gfpdf-copy-shortcode-button-606e9fbfa1c50`
4. The hover styles when the button is in the shortcode copied state should be green instead of the blue.

**Comment by jestonihpi** [comment]
Copy @jakejackson1.

**Comment by jakejackson1** [comment]
@jestonihpi also, have you tested the `catch` block to ensure it works correctly?

**Comment by jestonihpi** [comment]
Let me know what you think of this one @jakejackson1  : https://jsfiddle.net/kxodnhr6/8/
I've initially set the timer to 3secs.

Thanks!

**Comment by jestonihpi** [comment]
> @jestonihpi also, have you tested the `catch` block to ensure it works correctly?

The added code works, just to be safe  I will replicate the scenario with disabled clipboard-copy.

**Comment by jakejackson1** [comment]
@jestonihpi cool.

1. Let's go with 5000ms delay to reset it. 
1. I also recommend we wrap the text in a span and just update that span. Saves us having to also update the dashicon and means less code to reset.
1. To get the right effect on success right after clicking the button, we should do this:

```
.btn.btn-success,
.btn.btn-success:hover {
  color: #080;
  border-color: #080;
}
```

**Comment by jestonihpi** [comment]
Hi @jakejackson1, What do you think about this ? 
https://jsfiddle.net/kxodnhr6/12/

Thanks!

**Comment by jakejackson1** [comment]
Not sure what's going on now, but it doesn't reset back to its initial stage after 5000ms. The last fiddle has much closer to what we need.

**Comment by jestonihpi** [comment]
Hi @jakejackson1 . Sorry I posted the wrong link :(, here's the updated one :https://jsfiddle.net/kxodnhr6/12/

**Comment by jakejackson1** [comment]
@jestonihpi looks great! Let's start integrating this in Gravity PDF.
