### ISSUE TITLE
Prevent upgrade to v6 if Gravity Forms minimum requirement isn't met

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#1251]
**Description**
WordPress will check PHP ~and WP versions~ and prevent an upgrade to a release that isn't compatible (https://core.trac.wordpress.org/ticket/43987). We should consider extending this behaviour to check the Gravity Forms version so that users don't upgrade to v6 and then have to downgrade right away if they aren't ready to upgrade to 2.5. 

On the other hand, upgrading to 6.0 and then getting an error about an outdated version of Gravity Forms would encourage users to upgrade Gravity Forms as well, which would encourage users to keep up to date.

**Comment by jakejackson1** [comment]
A user reported being auto upgraded to version 6 because they have automatic plugin updates enabled. This is very problematic as it is an unassisted update and could leave the PDF-generation feature non-functional for an extended period of time.

**Comment by jakejackson1** [comment]
This will depend on how easy / hard it is to modify WordPress' plugin update system, but the ideal solution would be to:

1. Show there is a new update available, but prevent the user from updating if they don't meet the minimum requirements
2. Prevent auto-upgrade routine from running if minimum requirements aren't met
3. Allow any minor release (5.x) updates, even if users cannot upgrade to the next major release

**Comment by jestonihpi** [comment]
Are we going to update these lines @jakejackson1 ? https://github.com/GravityPDF/gravity-pdf/blob/62da8344023c4dc71ad7f7962e380dc921577457/src/Helper/Licensing/EDD_SL_Plugin_Updater.php#L109-L138

Or were going to create a separate method for this requirement check?

**Comment by jakejackson1** [comment]
@jestonihpi no. That file has nothing to do with how Gravity PDF core updates. The updates are managed by WordPress directly. This is a complex task and something I should look into personally.

**Comment by jestonihpi** [comment]
Copy @jakejackson1.

**Comment by jakejackson1** [comment]
Fixed in https://github.com/GravityPDF/gravity-pdf/pull/1280
