### ISSUE TITLE
PDF Template - Colossus needs an update 

### ISSUE THREAD

**Issue by jestonihpi** [GravityPDF/gravity-pdf#1261]
**Description**
Colossus needs to match up with the pdf column settings.
**Step To Reproduce**
1. Go to 'Forms -> Settings -> PDF'
2. Install and Select Colossus Template
3. Add a test entry and View Colossus template

**Expected behavior**
Edit : This should match up with the PDF Column Settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/434866/114328145-4027f380-9b6e-11eb-923a-3d0d51c83ee3.png)
![image](https://user-images.githubusercontent.com/434866/114339617-36ab8500-9b88-11eb-967e-51f7e95b45dc.png)

**Additional context**
As per Jake's advice - we were going to enforce the legacy mark up.

**Comment by jakejackson1** [comment]
To clarify, the expected result is NOT to match the gf2.5 columns. It's to match the PDF configuration column setting.

**Comment by jakejackson1** [comment]
Issue solved in latest commit of https://github.com/GravityPDF/template-universal-colossus. Need to finalise testing and then release.
