### ISSUE TITLE
Preview needs updating

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#1266]
Error message `Undefined array key "query"` being generated

**Comment by jestonihpi** [comment]
@jakejackson1 , I have look into this issue and it seems we just need to define this key as a non-nullable entity once it doesn't exists. eg `$document_url      = implode( '?', array_filter( [ $rest_endpoint_url['path'], $rest_endpoint_url['query'] ?? '' ] ) );`. Let me know what you think?

**Comment by jakejackson1** [comment]
@jestonihpi while Gravity PDF 6.0 will be PHP7.3+, the add-ons will still need to be compatible with v5 (for now), which means PHP5.6+ support. The `??` feature wasn't available until 7.0, so you'll need to do an `isset()` + ternary `?` check on `query`.

**Comment by jestonihpi** [comment]
PR created for this issue : https://github.com/GravityPDF/gravity-pdf-previewer/pull/93

**Comment by jakejackson1** [comment]
Shipped this update.
