### ISSUE TITLE
Font Manager - Add Font - TypeError: a.t0.json is not a function

### ISSUE THREAD

**Issue by jestonihpi** [GravityPDF/gravity-pdf#1275]
**Description**
When adding a font, the spinner does not go away and it seems unresponsive. Upon checking the console - I found out this error :
![image](https://user-images.githubusercontent.com/434866/116013869-f9a1c100-a664-11eb-9628-4957ec2ee107.png)

**Step To Reproduce**
1. Go to 'Forms -> Settings''
2. Click on 'PDF -> Tools tab'
3. Click Manage and Install a test font.

**Expected behavior**
This should work as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/434866/116014014-a2502080-a665-11eb-8ea0-84af60855d67.png)

**Additional context**
Versions Used.
WP - 5.7.1
Gravity Forms - 2.5-rc-3
Gravity PDF - 6.0.0

**I have tested this with a new local WP environment with the exact versions, however did not successfully replicated this issue.**

**Comment by jakejackson1** [comment]
@jestonihpi I believe this problem occurs if the API returns a non-JSON response i.e for example if a PHP notice occurred

**Comment by jakejackson1** [comment]
Cannot be replicated.
