### ISSUE TITLE
PDF not displayed when security enabled

### ISSUE THREAD

**Issue by blueliquiddesigns** [GravityPDF/gravity-pdf#15]
> PDF not showing when security enabled. I have enabled security to Yes & chose password from a field value. It does not showing the PDF file.

We've had the above report. Will need to investigate further.

**Comment by blueliquiddesigns** [comment]
Investigated the issue further but have not been able to replicate yet. Will leave open for the time being and see if any other users experience a similar problem.

**Comment by tareqhi** [comment]
Yup, same goes here. I could not able to see the PDF content when security enabled but if security is disabled, the PDF rendered.

**Comment by blueliquiddesigns** [comment]
Hi @tareqhi. You'll need to provide additional information about the exact settings you used (screenshots will help) and the error messages (if any) received when attempting to view the PDF. You should also try download the PDF and open it on your desktop to see if that works. 

As the note says, we haven't been able to replicate this issue.
