### ISSUE TITLE
Include Bengali Font Face

### ISSUE THREAD

**Issue by blueliquiddesigns** [GravityPDF/gravity-pdf#17]
Integrate GPLv2 Mukti (Freedom) font from http://www.nongnu.org/freebangfont/downloads.html

**Comment by tareqhi** [comment]
Thanks a lot

**Comment by blueliquiddesigns** [comment]
Bengali Font Face support resolved in https://github.com/blueliquiddesigns/mpdf/commit/ffd84e741e44edcc436f8b8729c4b39af5d9472c
