### ISSUE TITLE
Welcome Page showing inappropriately 

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#324]
We installed the Gravity Forms Logging plugin on a client's website and when activated it triggered Gravity PDF's Update Page redirect. Do more testing about when and why this happens.

**Comment by blueliquiddesigns** [comment]
Also, had permissions error viewing said welcome page. Need to look into it more too.

**Comment by jakejackson1** [comment]
Did testing. Was able to resolve the permissions problem but haven't been able to track down the incorrect redirect bug yet. Going to mark this as unconfirmed until we are able to replicate.
