### ISSUE TITLE
Custom header/footer rich text editor stuck in "visual" mode.

### ISSUE THREAD

**Issue by JulianT2013** [GravityPDF/gravity-pdf#339]
When creating or editing, and before saving, a PDF, the custom header/footer rich text editor gets stuck in "visual" mode regardless of which tab you select. 

![rich text bug2](https://cloud.githubusercontent.com/assets/5170289/14971875/ee0dd40e-1119-11e6-9773-123e4cf67a19.JPG)

Clicking "Add PDF" and then going back to edit it has the following results:

![converted](https://cloud.githubusercontent.com/assets/5170289/14971948/997b5fc8-111a-11e6-8bf7-b2509e772ff4.JPG)
(ie. HTML tags are converted to plain text)

Also, clicking on "visual" sometimes brings up two rich text editors (as if showing them one on top of the other instead of switching between visual/text).

![double](https://cloud.githubusercontent.com/assets/5170289/14971852/b8f6f926-1119-11e6-99aa-424a1c24a750.JPG)

**Comment by jakejackson1** [comment]
This is an intermittent problem that I haven't been able to track down yet. It only effects some users some of the time. Need to be able to replicate all the time / more data to debug further.

**Comment by jakejackson1** [comment]
Until more information comes to light I'm closing this issue.
