### ISSUE TITLE
PDF Master Password

### ISSUE THREAD

**Issue by tareqhi** [GravityPDF/gravity-pdf#357]
Hi in v3, we have a option to setup master password for PDF files with "pdf_master_password".
Where is this setting/configuration in v4?

**Comment by jakejackson1** [comment]
Thanks for the feedback.

We made a conscious decision to not include a Master Password UI in 4.0. We felt the Master Password concept for many users would be too confusion. Along with that, there is a lot less need for a master password as you can easily modify the PDF privileges through Gravity PDF and regenerate a PDF. 

With that said, it may be convenient for power users to have a UI to add a master password that can be turned on user a simple WordPress filter. We'll think about this possibility further.

**Comment by jakejackson1** [comment]
We're going to leave this out of the 4.0 release and get further feedback from other users before deciding whether to add this in via a filter.
