### ISSUE TITLE
Merge Tag in PDF Security

### ISSUE THREAD

**Issue by tareqhi** [GravityPDF/gravity-pdf#358]
I just tested with v4.03, I got a problem with PDF security. If I set the password for PDF from a field value with merge tag, it does not accepts the password.
Is there any problem with merge tag in PDF password?

**Comment by jakejackson1** [comment]
Thanks for the feedback. This in indeed a bug and I've submitted two PRs that together will resolve the problem once they have been merged in.

**Comment by tareqhi** [comment]
Not resolved the issue. Plz check

**Comment by jakejackson1** [comment]
As I said, the PRs first need to be merged (once fully tested). You then would need to update the plugin files on your website to test it out.

**Comment by jakejackson1** [comment]
This PR has now been merged in. If you [download the development branch](https://github.com/GravityPDF/gravity-pdf/archive/development.zip), unzip it and upload to /wp-content/plugins/gravity-forms-pdf-extended/ on your server (set your FTP client to override all files) you'll be able to test out the fix.

**Comment by tareqhi** [comment]
Thanks, I've tested the changes. It works.
