### ISSUE TITLE
WP External Links Plugin Conflict

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#386]
In 3.7.7 user had trouble generating PDF with the WP External Links plugin active (https://wordpress.org/plugins/wp-external-links/). Test it out and see if there is a problem.

**Comment by TheWebmasterCo** [comment]
I can confirm this behavior in 4.0.4 -

The plugin author has a FAQ where he outlines some filters and methods to alleviate.

[https://wordpress.org/plugins/wp-external-links/faq/]

Using _wpel_apply_settings_ you might be able to work something in at runtime, but to ignore all links he is looking for a class or link attribute. Not sure how helpful those will be. As more time permits down the road, I might be able to revisit and try a few solutions.

**Comment by jakejackson1** [comment]
A patch for this will be available in Gravity PDF 4.1.
