### ISSUE TITLE
Create an advanced template manager

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#486]
Utlise the design of the theme manager, an create a JS-powered template manager to view, select, delete or install new templates. 

This will compliment the new template shop which will be timed with this release.

**Comment by odyright** [comment]
Hello, what about the final release?

**Comment by jakejackson1** [comment]
Hi @odyright, this feature is currently scheduled for Gravity PDF 4.1 and will be released at that time (there is no time line for this).

**Comment by odyright** [comment]
ok. Now, Is Gravity pdf support html5 & Css3 or such new design like Maaterial design? i asked, because i have a custum template made with it.

**Comment by jakejackson1** [comment]
> Now, Is Gravity pdf support html5 & Css3 or such new design like Maaterial design? i asked, because i have a custum template made with it. 

There's [very limited support for HTML5 / CSS3 features](http://mpdf.github.io/css-stylesheets/supported-css.html). However, this is not the correct location to ask such as question. [Please use our support ticket system](https://gravitypdf.com/support/). GitHub issues are for reporting bugs related to Gravity PDF.

**Comment by odyright** [comment]
ok thanks!
