### ISSUE TITLE
will gravity form 2.0 be supported?

### ISSUE THREAD

**Issue by lubobill1990** [GravityPDF/gravity-pdf#487]
Currently, gravity pdf support gravity form 1.9, is there a plan that gravity form 2.0 be supported?

**Comment by jakejackson1** [comment]
Gravity Forms 2.x is already supported. The minimum required version of Gravity Forms is 1.9.

**Comment by lubobill1990** [comment]
Thanks. Perhaps there's some problems with the configuration at that time. It can be used now.
