### ISSUE TITLE
HTML Entities in PDF Filenames

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#499]
We've still experiencing HTML entity issues in the PDF filenames. Take a closer loop.

**Comment by jakejackson1** [comment]
It appears to happen when special characters are used in merge tags

**Comment by jakejackson1** [comment]
Surprisingly that issue doesn't occur in Gravity PDF 4.0.5...

**Comment by norbertpapp** [comment]
It does still occur in Gravity PDF 4.0.5 for one of my client, using custom template.

 The output PDF: 
[termekdij-nyilatkozat-vareg-hungary-kft.pdf](https://github.com/GravityPDF/gravity-pdf/files/534767/termekdij-nyilatkozat-vareg-hungary-kft.pdf)

The custom template code:
`<?php
/**
 * Don't give direct access to the template
 */ 
if(!class_exists("RGForms")){
	return;
}

/**
 * Load the form data to pass to our PDF generating function 
 */

$form = RGFormsModel::get_form_meta($form_id);
?>

<!DOCTYPE html>
<html>
<head>	
<meta charset="UTF-8">
    <link rel='stylesheet' href='<?php echo PDF_PLUGIN_URL .'initialisation/template.css'; ?>' type='text/css' />
	<?php 
		/* 
		 * Create your own stylesheet or use the <style></style> tags to add or modify styles  
		 * The plugin stylesheet is overridden every update		 
		 */
	?>
    <title>Gravity PDF</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<style type="text/css">
		html, body, div, form, fieldset, legend, label
		{
		 margin: 0;
		 padding: 0; 
		}
		table
		{
		 border-collapse: collapse;
		 border-spacing: 0;
		}
		th, td
		{
		 text-align: left;
		 vertical-align: top;
		}
		h1, h2, h3, h4, h5, h6, th, td, caption { font-weight:normal; }

		img { border: 0; }
		body {
			width: 960px;
			margin: 2em auto;
			border: 1px solid #dcdcdc;
			padding: 2em;
			font-family: 'Segoe UI', Calibri, Candara, Segoe, "Segoe UI", Optima, Arial, sans-serif0;
		}
		.row {
		  width: 100%;
		  overflow: auto;
		}
		.row p {  padding: 0.5em;}
		.label {width: 35%; float: left; display: inline-block;}
		.data {width: 65%; float: left; display: inline-block;}
		.data p {
		  border: 1px solid #000000;
		}
		ul li {
		  list-style-type: none;
		}
		.header {text-align: right;}
		.header img {float: left;}
		span.underline {
			width: 30%;
			margin-left: 1em;
			display: inline-block;
			border-bottom: 1px solid;
			padding: 0 2em;
		}
		.signature {text-align: right;}
		.row p {margin: 5px 0;}
	</style>
</head>
	<body>
        <?php	
        foreach($lead_ids as $lead_id) {
            $lead = RGFormsModel::get_lead($lead_id);
            $form_data = GFPDFEntryDetail::lead_detail_grid_array($form, $lead);
			/*
			 * Add &data=1 when viewing the PDF via the admin area to view the $form_data array
			 */
			PDF_Common::view_data($form_data);
			/*
			 * Store your form fields from the $form_data array into variables here
			 * To see your entire $form_data array, view your PDF via the admin area and add &data=1 to the url
			 * For an example of accessing $form_data fields see https://developer.gravitypdf.com/documentation/custom-templates-introduction/
			 *
			 * Alternatively, as of v3.4.0 you can use merge tags (except {allfields}) in your templates. 
			 * Just add merge tags to your HTML and they'll be parsed before generating the PDF.	
			 * 		 
			 */				 					
			$signature = $form_data['signature']['0'];
			?>
<div class="header">
	<img id="logo" src="http://vareg.hu/wp-content/themes/Bootstrap-3-blank-wordpress-theme-master/img/vareg-logo-hun.png" />
	<h1>Termékdíj nyilatkozat</h1>
	<h3>Vareg Hungary Kft-nél készült termékekre</h3>
	<small>(* Csillaggal jelölt mező kitöltése kötelező)</small>
</div>
<div class="row">
  <div class="label">
    <p>Kapcsolattartó:</p>
  </div>
  <div class="data">
    <p>{Kapcsolattartó::4}</p>
  </div>
</div>
<div class="row">
  <div class="label">
    <p>*Cégnév:</p>
  </div>
  <div class="data">
    <p>{Cégnév::2}</p>
  </div>
</div>
<div class="row">
  <div class="label">
    <p>*Cím:</p>
  </div>
  <div class="data">
    <p>{Cím::13}</p>
  </div>
</div>
<div class="row">
  <div class="label">
    <p>*Adószám:</p>
  </div>
  <div class="data">
    <p>{Adószám::14}</p>
  </div>
</div>
<div class="row">
  <div class="label">
    <p>*Kalkulációs szám:</p>
  </div>
  <div class="data">
    <p>{Kalkulációs szám::15}</p>
  </div>
</div>
<p>Ezúton nyilatkozom, hogy az általam a Vareg Hungary Kft-től megrendelt kalkulációs számú termék 
  a 2011. évi LXXXV: törvény alapján <b>reklámhordozó papírnak nem minősül.</b>
</p>
<form>
<ul>
  <li><img src="http://cdns2.freepik.com/free-photo/checked-form-circle_318-30321.jpg" style="height: 8px;" />  {Egyik mezőt kérjük bejelölni:7} {ISBN vagy ISSN szám:17}</li>
</ul>
</form>
<small>Tudomásul veszem, hogy a jelen nyilatkozatot, mely a fentiekben megjelölt jogszabályok rendelkezései alapján szükséges, a Vareg Hungary Kft. a Ktdt. rendelkezéseinek megfelelően megőrzi. Tudomásul veszem, hogy csomagolószer esetén abban az esetben, ha a nyilatkozó a termékdíj-kötelezettség kapcsán tett nyilatkozattal ellentétesen jár el, illetve a csomagolószert nem, vagy nem a nyilatkozat tartalma szerinti mértékben és módon használja fel, illetve a felhasználás tényét nem tudja igazolni, úgy az elmaradt termékdíjat és a csomagolószer beszerzésének időpontjától számított késedelmi pótlékot köteles megfizetni.  Tudomásul veszem, hogy belföldi előállítású reklámhordozó esetén a nem a valóságnak megfelelően nyilatkozó megrendelő – a Ktdt-ben meghatározottak szerint – termékdíj-kötelezetté válik.
A megrendelő által tett nyilatkozat tartalmáért a Vareg Hungary Kft. nem felel.
</small>
<div class="footer">
  <p>Kelt: <span class="underline">     {Kelt::8}     </span><br>Dátum: <span class="underline">     {Dátum:10}     </span></p>
  <p class="signature">
  	<span class="underline">    <img style="max-height: 100px;" src="<?php echo $form_data['signature_details_id'][11]['path']; ?>" />     </span><br>
  	<span>cégszerű aláírás</span>
  </p>
  <p class="signature">pecsét helye</p>
</div>
         {all_fields}
        <?php } ?>
	</body>
</html>`

**Comment by jakejackson1** [comment]
Your issue is unrelated to this ticket (the ticket is specifically talking about the PDF filename). Your issue can be resolved by using the [Font Manager to install Arial as a custom font](https://gravitypdf.com/documentation/v4/user-custom-fonts/). Ensure you name the font "Arial A" as using "Arial" will cause a conflict with the core PDF fonts, and then update the `font-family` in your custom template.

**Comment by norbertpapp** [comment]
Thank you @jakejackson1 , using custom font just solved the problem, much obliged.
