### ISSUE TITLE
Send a PDF with a button and/or an ACTION inside.

### ISSUE THREAD

**Issue by PietroSferrino** [GravityPDF/gravity-pdf#504]
Hello Guys ...
I am very new here and on Gravity PDF ... which looks SUPER! Great Job! 

By the way ...
I am wondering ... After submitting a Gravity Form, can I automatically SEND via e-mail to 1 or MORE than 1 person, a PDF with inside a CONFIRMATION BUTTON ???

Something like: ACCEPT QUOTATION ...
And an action like sending other e-mails (for example to the ACCOUNTANT, in order to build the invoice after a customer accept the quotation) ???

Tricky, yes ???

I hope I did explain well what I need.

MANY THANKS!!!

Pietro ^_^

**Comment by jakejackson1** [comment]
Hi Pietro,

Sure. Gravity PDF comes with automated PDF to email functionality out of the box. You'll need to [create a custom PDF](https://gravitypdf.com/documentation/v4/developer-start-customising/) so you can include a "button" (I'd use an image that looks like a button and wrap it in a link tag). I'd suggest linking to a 2nd form showing a summary of the quote (custom code needed) which the user has to complete to "accept". You can then setup notifications for your accountant, or anyone else. 

For future questions like this, please [use our support ticket system](https://gravitypdf.com/support/). Github issues are purely for bug reports and developers to discuss how to implement new features.
