### ISSUE TITLE
Have no 'configuration.php' file in Gravity PDF Installation

### ISSUE THREAD

**Issue by morganca** [GravityPDF/gravity-pdf#576]
I have Wordpress Multisite running and have searched through all my files for the "configuration.php" file to make changes to create some PDFs in templates, but there is no configuration.php file for Gravity PDF.

When I've looked over the documentation, the file structure is different to what I have installed after downloading the plugin.

For each multisite installation, I have the multisite number, then "config" folder that just has the templates, and "images".  But none of the other folders shown in your documentation.

How do I fix this?  I can create pdfs and send them so it's working, but I can't access the configuration.php file to make the changes to enable landscape PDFs.
![gfpdfconfigfolderpluginfolder2](https://cloud.githubusercontent.com/assets/25227883/22114963/2776566e-de63-11e6-88ce-e0761d2221a0.JPG)

**Comment by jakejackson1** [comment]
Gravity PDF v4 doesn't use a `configuration.php` file (which based on the folder structure you have is what you are using). [PDFs are setup from your WP Admin area](https://gravitypdf.com/documentation/v4/user-setup-pdf/). 

Since it sounds like you are familiar with Gravity PDF v3 [I recommend reviewing the v3 to v4 upgrade guide](https://gravitypdf.com/documentation/v4/v3-to-v4-migration/#upgrading-to-v4) to see all the changes.

**Comment by morganca** [comment]
But I don't understand then how I change a PDF to being landscape. Because
I create custom PDF templates, it no longer gives me the option to choose
landscape in the wp-admin area. So where do I insert code to change to
landscape? I've tried doing it directly in the template but it doesn't work
using @page rules. I'm really stuck, could you please help as I've had the
problem for over a weeks and can't find a way forward.

**Comment by jakejackson1** [comment]
All v4 templates have the option to set the orientation [in the Appearance tab](https://gravitypdf.com/documentation/v4/user-setup-pdf/#appearance-tab) when configuring a PDF in the UI. [Review the v4 documentation on custom templates](https://gravitypdf.com/documentation/v4/developer-first-custom-pdf/) to correctly create / convert your current template. 

If you have any further questions [please open a support ticket on our website](https://gravitypdf.com/support).

**Comment by morganca** [comment]
Ignore this sorry, I am an idiot - the option is there, I have tried so
many things and looked at this and couldn't find it.  I don't understand
how I missed it so much, apologies,

Carrie
