### ISSUE TITLE
Exclude some element without css

### ISSUE THREAD

**Issue by StudioOsiris** [GravityPDF/gravity-pdf#618]
Hello to Australia from Czech republic,
How can I exclude some element from pdf? When I put css "exclude", it works fine, but how exclude element without css possibility, like here: https://gravitywiz.com/documentation/gravity-forms-unique-id/ There is not possible css, so mayby put somthing to function.php?

**Comment by jakejackson1** [comment]
Hi @StudioOsiris. Thanks for your question.

We're aware of the limitation with the CSS "exclude" option for certain fields that don't support a CSS property. Eventually we'd like to create an advanced PDF builder to prevent the need to use CSS in the form editor, but that's a long term goal.

In the interim you have a couple options available:

1. Create a [custom PDF template based off one of the core templates](https://gravitypdf.com/documentation/v4/developer-first-custom-pdf/) and use the CSS property `display: none` to hide the field from the PDF.

2. Use the action [gfpdf_core_template](https://gravitypdf.com/documentation/v4/gfpdf_core_template/) to apply the same method as described above.

**Comment by StudioOsiris** [comment]
Hi,
Thank You for reply,
I try it long time, but no result.
How can I putt css name for specific field?
For ex: I have field with name "Unique ID" and ID "29", so I can apply this?:

add_action( 'gfpdf_core_template', function() {
    ?>
        <style>
field_ID:29 {
    display: none
}
        </style>
    <?php

} );

**Comment by StudioOsiris** [comment]
Hi,
Thank You for reply,
I try it long time, but no result.
How can I putt css name for specific field?
For ex: I have field with name "Unique ID" and ID "29", so I can apply
this?:

add_action( 'gfpdf_core_template', function() {
?>
<style>
field_ID:29 {
display: none
}
</style>
<?php

} );

2017-05-02 23:58 GMT+02:00 Jake Jackson <notifications@github.com>:

**Comment by jakejackson1** [comment]
Hi @StudioOsiris, you can find the correct field ID by viewing the PDF in the admin area and [use the "html" helper parameter](https://gravitypdf.com/documentation/v4/development-helper-parameters/#html). This will allow you to inspect the HTML markup (using your browsers dev tools) and correctly target your field in CSS. 

The correct code should be:

`
#field-29 {
   display: none;
}
`

**Comment by StudioOsiris** [comment]
Hi,
OK, It works fine.
But when I add style to table (<table style="border: 2px solid #000000;">) it show without. Why?

**Comment by StudioOsiris** [comment]
I have this code:
`<table style="height: 353px; width: 825px;">
<tbody>
<tr style="height: 92.4833px;">
<td style="width: 877.133px; height: 92.4833px;" colspan="3"><img src="http://t4app.studioosiris.cz/wp-content/uploads/2017/05/t4building-150x25.png" alt="" width="276" height="46" /></td>
<td style="margin-left: 120px;">
<table style="border: 2px solid #000000;">
<tbody>
<tr style="height: 93px;">
<td style="height: 93px;">
<p style="padding-left: 30px; padding-top: 30px;">T4 Building s.r.o. Vratimov, Buničitá 1132, PSČ 739 32 IČ: 04352530 DIČ: CZ04352530</p>

<table>
<tbody>
<tr>
<td></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
&nbsp;</td>
</tr>
<tr style="height: 32px;">
<td style="width: 877.133px; height: 32px;" colspan="3"></td>
<td style="width: 622.933px; height: 32px;">22800859</td>
</tr>
<tr style="height: 32px;">
<td style="width: 877.133px; height: 32px;" colspan="3">Ulice:</td>
<td style="width: 622.933px; height: 32px;">Zeměchy 181</td>
</tr>
<tr style="height: 32px;">
<td style="width: 877.133px; height: 32px;" colspan="3">PSČ, město:</td>
<td style="width: 622.933px; height: 32px;">440 01 Jimlín</td>
</tr>
<tr style="height: 32px;">
<td style="width: 877.133px; height: 32px;" colspan="3">mob./tel.</td>
<td style="width: 622.933px; height: 32px;">734780551</td>
</tr>
<tr style="height: 32px;">
<td style="width: 877.133px; height: 32px;" colspan="3">Email:</td>
<td style="width: 622.933px; height: 32px;"></td>
</tr>
<tr style="height: 32px;">
<td style="width: 191px; height: 32px;">Objednávka číslo:</td>
<td style="width: 230px; height: 32px;">100002017</td>
</tr>
<tr style="height: 32px;">
<td style="width: 191px; height: 32px;">V Kolíně dne:</td>
<td style="width: 230px; height: 32px;">24.04.17</td>
</tr>
</tbody>
</table>
&nbsp;`
And its without border in pdf:
http://imgur.com/a/AMBbt
So what is wrong?

**Comment by jakejackson1** [comment]
`#0` isn't a valid hex colour code. I also recommend applying the borders to the table cells `td` instead of the table itself. 

Also note, Mpdf, the software we use to generate PDFs, doesn't support all CSS. [Read their docs for more info](https://mpdf.github.io/css-stylesheets/supported-css.html).

**Comment by StudioOsiris** [comment]
Hi,
OK., when I add css under cells td it works.
Now I cannot resolve Styles for Horizontal Rules (hr CSS Design) - see here: https://codepen.io/ibrahimjabbari/pen/ozinB.
When I add "hr.style2 {
    border-top: 3px double black;
}"
So it not works, can You help me with This?

**Comment by TheWebmasterCo** [comment]
These are the only supported properties for hr : 

width, text-align, color, height, margin (all), clear

https://mpdf.github.io/css-stylesheets/supported-css.html

**Comment by StudioOsiris** [comment]
OK.
I have this text:
http://imgur.com/a/cPNM1
But there is lot of space,  I need lesser space there (line-height), like here:
http://imgur.com/a/st0Ew
How can I resolve it (via css)?

here is my code:
https://codeshare.io/5vKgvm

**Comment by TheWebmasterCo** [comment]
A few ways. Simplest, probably change your spans to div's and use a negative margin.

`<div style="font-family: 'Open Sans';margin-bottom:-10px;">`

**Comment by StudioOsiris** [comment]
OK.
I have this text:
http://imgur.com/a/cPNM1
But there is lot of space,  I need lesser space there (line-height), like here:
http://imgur.com/a/st0Ew
How can I resolve it (via css)?

here is my code:
https://codeshare.io/5vKgvm

**Comment by StudioOsiris** [comment]
Hi,
div´s dont work for me,
I change it:
https://codeshare.io/2jeJnM
in gravitypdf editor looks good:
http://imgur.com/a/gc4Iq
But in PDF still some result:
http://imgur.com/a/ccxx3
Any Idea?

**Comment by TheWebmasterCo** [comment]
It's margin-bottom, not just margin. You'll need to know some CSS basics to get this to work how you want. 

Any of the issues you are facing are UI related and not related to GravityPDF not rendering properly - it just uses mPDF. So you'll have to mess with and learn CSS a bit more to get it tweaked to how you want it.

**Comment by StudioOsiris** [comment]
I try margin-bottom too, but not work! In editor its good, but generated PDF without -10 margin-bottom.

**Comment by StudioOsiris** [comment]
Just "<hr style="margin-top: -3;margin-bottom: 3;" />", thats it.
