### ISSUE TITLE
Fatal error about missing class .../vendor/composer/autoload_real.php on line 30

### ISSUE THREAD

**Issue by lordspace** [GravityPDF/gravity-pdf#661]
I have moved a WP site to Ubuntu 16 with php 7.0 and I got this error.

`Fatal error: Uncaught Error: Class 'Composer\Autoload\ComposerStaticInitf19b525757c4d2ef00e410d42c87798b' not found in /var/www/vhosts/troubleshooting/example.com/example.com_2017_07_12_wpe/wp-content/plugins/gravity-forms-pdf-extended/vendor/composer/autoload_real.php on line 30`

**Comment by jakejackson1** [comment]
That error suggests the Gravity PDF plugin wasn't migrated successfully. [Just reinstall the plugin via FTP and you'll be good to go](https://downloads.wordpress.org/plugin/gravity-forms-pdf-extended.4.2.1.zip).
