### ISSUE TITLE
Missing vendor packages with installation through wpackagist.org

### ISSUE THREAD

**Issue by rexxnar** [GravityPDF/gravity-pdf#695]
Hello,

With the installation through [wpackagist.org](https://wpackagist.org/) from version 4.2.2 to 4.3.0 it removes the following vendor packages:

> codeguy
> composer
> masterminds
> monolog
> psr
> querypath
> setasisgn

The package that is not removed is this one:
>blueliquiddesigns

With the removal of composer the autoload is failing and the websites running 4.3 will get a php error. If i update the plugin through WordPress it self these packages are getting installed. So something is wrong with the connection through wpackagist.org. Im not sure if this is the correct place to address the issue. We are currently updating though composer so installing within WordPress itself is not an option. For now we have locked the plugin to 4.2.2.

thanks.

**Comment by jakejackson1** [comment]
Hi, 

I haven't had any issues loading the plugin via Wpackagist. Run `composer clear-cache` and try v4.3 again.

**Comment by rexxnar** [comment]
It had something to do with our proxy, problem was solved when i deleted the cache in there :)! thank you for your fast reply.
