### ISSUE TITLE
Merge tag {qrcode:filenames} print a path with double slash

### ISSUE THREAD

**Issue by edubacco** [GravityPDF/gravity-pdf#705]
Using the {qrcode:filenames} and {qrcode:imagelinks} merge tags will print a path or url with a double back slash, i.e.:
`/path/with/double//back/slash.png`
To avoid this, in file `class.gravityforms_qrcode.php` line 311 and 312 we have to delete the slash after the `plugin_dir_path()` and `plugin_dir_url()` funcions

**Comment by jakejackson1** [comment]
Gravity PDF doesn't include a file called `class.gravityforms_qrcode.php`. I believe you've reported this issue to the wrong package.
