### ISSUE TITLE
Forced new lines in Rich Text editor shows as <br> in PDF

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#712]

**Comment by ado2000** [comment]
Hi, the same problem for me.

[gravityform id="10" title="true" description="true" field_values="nome_prodotto=product name&prezzo_prodotto=99,00&quantita_prodotto=1&descrizione_prodotto=First line text
Second line text
Thirty line text
Fourth line text "]

In this case, i see some <br /> tags into the pdf at the end of each description line

**Comment by jakejackson1** [comment]
@ado2000 thanks for the additional details. Unfortunately in my testing I still wasn't able to replicate any problem with the Rich Text Editor field. 

![pdf-rich-text-field](https://user-images.githubusercontent.com/2918419/33193629-28751182-d11e-11e7-9033-bc94953c15df.png)

Using a standard Paragraph field the `<br>` tags do show up at the end of each line in the form itself, but that is a Gravity Forms problem and unrelated to Gravity PDF. If you temporarily disable all plugins except Gravity Forms and Gravity PDF, then submit a new entry does the problem still occur for the Rich Text Editor field in the PDF?
