### ISSUE TITLE
Add Option to Print or Download PDFs from Entries Bulk Action

### ISSUE THREAD

**Issue by pengie5696** [GravityPDF/gravity-pdf#797]
Love this plugin, but see that this new feature might be extremely helpful if you would consider adding it.

The use case is where there are many entries as with my client who has many Camp Registration Forms and it would be much easier to access all PDF versions of form entries and print them for a fast booklet to provide to Camp Counselors etc.  

The ability to Bulk Print PDFs using the checkbox to select entries and then Bulk Actions to select either Print PDF or even Download PDF (even better if that created a zip file) and then Apply.  I see no way to do this from the dashboard.

**Comment by jakejackson1** [comment]
@pengie5696 bulk PDF generation / download [is already on our features list](https://trello.com/c/1arQDzFs/5-allow-multiple-pdfs-to-be-generated-and-downloaded-in-a-zip-file). 

I'm closing this issue as Github is solely for developer collaboration and not feature requests. If you've further questions or feedback, [please submit it via our support system](https://gravitypdf.com/support/).
