### ISSUE TITLE
Mass download pdf entries

### ISSUE THREAD

**Issue by klikict** [GravityPDF/gravity-pdf#807]
Hi, 
It would be great if it is possible to mass download all the PDF's from a specific selection ( date f.e ). We are having some issues with all of our entries, and we now have to do it manually.

**Comment by jakejackson1** [comment]
[This is on our roadmap](https://trello.com/c/1arQDzFs/5-allow-multiple-pdfs-to-be-generated-and-downloaded-in-a-zip-file) and onc of the next features we'll be focusing on once Gravity PDF v5 is launched.
