### ISSUE TITLE
Create new PDF URL that's used for limited public access

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#826]
This would be an alternative option that would allow users access to the link for as long as the TTL is valid. Uses include: 

- Public authentication when the IP address isn't saved
- Less restrictions when being emailed
- Use with WooCommerce's Download Feature and the Woo Gravity Forms plugin

Will need to consider how to store and process the data (options table vs custom table vs alternate table). 

Will need to consider how to integrate into the current [gravitypdf] shortcode and PDF merge tag, and the different Confirmation types.

**Comment by jakejackson1** [comment]
Shipped in https://github.com/GravityPDF/gravity-pdf/pull/841

**Comment by JorgeDDW** [comment]
Hey there!
I need to ask, with this enhancement, I can generate a pdf with Gravity PDF, Gravity Woocommerce and Woocommerce?

**Comment by jakejackson1** [comment]
@JorgeDDW I don't believe it's currently available out of the box, no. What you can do right now is send the generated PDF with Gravity Forms Notifications that are triggered when your Gravity WooCommerce order is put through ([provided you've set this up](https://docs.woocommerce.com/document/woocommerce-gravity-forms-product-addons/#section-17)).
