### ISSUE TITLE
Webhook feature

### ISSUE THREAD

**Issue by berniezhao11** [GravityPDF/gravity-pdf#885]
Hi,

First of all great plugin!  Thank you for the wonderful work!
We are building a solution and we'd like to be notified when a PDF is generated so we can call some REST API to store it somewhere else.
Any suggestion is appreciated!

**Comment by jakejackson1** [comment]
Hi @berniezhao11,

[The `gfpdf_post_save_pdf` action hook will be useful here](https://gravitypdf.com/documentation/v5/gfpdf_post_save_pdf/). You can use it to send the PDF to a 3rd party service.
