### ISSUE TITLE
When RTL mode enabled, columns should be reversed

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#895]
For example, if a form has three fields in a three-column row, with RTL disabled it would display as follows:

Field 1 | Field 2 | Field 3

With RTL enabled, it should display as follows:

Field 3 | Field 2 | Field 1

**Comment by jakejackson1** [comment]
Rework CSS Ready Classes to the following format:

`
<?php if( ! $rtl ): ?>
	.gf_left_half,
	.gf_left_third, .gf_middle_third,
	.gf_first_quarter, .gf_second_quarter, .gf_third_quarter,
	.gf_list_2col li, .gf_list_3col li, .gf_list_4col li, .gf_list_5col li {
		float: left;
	}

	.gf_right_half,
	.gf_right_third,
	.gf_fourth_quarter {
		float: right;
	}
	<?php else: ?>
	.gf_left_half,
	.gf_left_third, .gf_middle_third,
	.gf_first_quarter, .gf_second_quarter, .gf_third_quarter,
	.gf_list_2col li, .gf_list_3col li, .gf_list_4col li, .gf_list_5col li {
		float: right;
	}

	.gf_right_half,
	.gf_right_third,
	.gf_fourth_quarter {
		float: left;
	}
	<?php endif; ?>

	.gf_left_half, .gf_right_half,
	.gf_list_2col li {
		width: 49%;
	}

	.gf_left_third, .gf_middle_third, .gf_right_third,
	.gf_list_3col li {
		width: 32.3%;
	}

	.gf_first_quarter, .gf_second_quarter, .gf_third_quarter, .gf_fourth_quarter {
		width: 24%;
	}

	.gf_list_4col li {
		width: 24%;
	}

	.gf_list_5col li {
		width: 19%;
	}

	<?php if( ! $rtl ): ?>
	.gf_left_half, .gf_right_half {
		padding-right: 1%;
	}

	.gf_left_third, .gf_middle_third, .gf_right_third {
		padding-right: 1.505%;
	}

	.gf_first_quarter, .gf_second_quarter, .gf_third_quarter, .gf_fourth_quarter {
		padding-right: 1.333%;
	}

	.gf_right_half, .gf_right_third, .gf_fourth_quarter {
		padding-right: 0;
	}
	<?php else: ?>
	.gf_left_half, .gf_right_half {
		padding-left: 1%;
	}

	.gf_left_third, .gf_middle_third, .gf_right_third {
		padding-left: 1.505%;
	}

	.gf_first_quarter, .gf_second_quarter, .gf_third_quarter, .gf_fourth_quarter {
		padding-left: 1.333%;
	}

	.gf_right_half, .gf_right_third, .gf_fourth_quarter {
		padding-left: 0;
	}
	<?php endif; ?>

	/* Don't double float the list items if already floated (mPDF does not support this ) */
	.gf_left_half li, .gf_right_half li,
	.gf_left_third li, .gf_middle_third li, .gf_right_third li {
		width: 100% !important;
		float: none !important;
	}
`

**Comment by jakejackson1** [comment]
Have included the code to handle this in core. Will need to upgrade the templates as well.

**Comment by jakejackson1** [comment]
@mcglenn07 when you've some free time we'll need to begin planning for updates to the Universal templates for Gravity PDF 6.0.

**Comment by mcglenn07** [comment]
Yes, Jake. thank you!
