### ISSUE TITLE
Checkbox checked

### ISSUE THREAD

**Issue by vlad57** [GravityPDF/gravity-pdf#925]
Hi guys, 

I have a problem with a custom PDF generation. I'm trying to check a checkbox with the property "checked" but it doesn't work.

Solutions ? 

Thanks a lot,

**Comment by jakejackson1** [comment]
Hi @vlad57,

What code have you tried in your custom PDF template?

**Comment by vlad57** [comment]
I'm sorry ! I found my error, I did this : <input type="checkbox" checked>, but it works like this : <input type="checkbox" checked="checked">. Stupid error !

**Comment by jakejackson1** [comment]
Glad you were able to work it out. Happy PDFing!

**Comment by ramrkp** [comment]
with `<input type="checkbox" checked="checked">` it gives me this


<img width="128" alt="Screenshot 2021-10-21 at 2 03 16 PM" src="https://user-images.githubusercontent.com/15122639/138241759-5a9ed708-fcdb-4e94-a6ee-0a480f9b017a.png">
