### ISSUE TITLE
Allow PDF Merge Tag to be used in AddOn Map Type

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#960]
This will allow the PDF URL to be sent with API requests to other services.

The basis for this functionality is as follows:

```
add_filter( 'gform_addon_field_map_choices', function( $fields, $form_id, $field_type, $exclude_field_types ) {
	$pdfs = GPDFAPI::get_form_pdfs( $form_id );

	foreach ( $pdfs as $pdf ) {
		$merge_tag = sprintf(
			'{%s:pdf:%s}',
			$pdf['name'],
			$pdf['id']
		);

		$fields[] = [
			'label' => $merge_tag,
			'value' => $merge_tag,
		];
	}

	return $fields;
}, 10, 4 );

add_filter( 'gform_addon_field_value', function( $field_value, $form, $entry, $field_id ) {
	if ( ! empty( $field_value ) || strpos( $field_id, ':pdf:' ) === false ) {
		return $field_value;
	}

	$mergetags = GPDFAPI::get_mvc_class( 'Model_Mergetags' );

	return $mergetags->process_pdf_mergetags( $field_id, $form, $entry, false );
}, 10, 4 );
```

**Comment by jakejackson1** [comment]
Should test the following add-ons to ensure it's working correctly:

- [x] PayPal
- [x] MailChimp
- [x] HubSpot - works with select box PDF value, but not if using a custom value and the Mergetag (doesn't appear to work if using a custom value set to a normal string and this appears to be a bug).
- [x] Gravity Flow
- [x] Stripe
- [x] Square
- [x] ActiveCampaign
- [x] Agile CRM
- [ ] AWeber
- [x] Breeze
- [x] Capsule
- [x] CleverReach
- [x] Constant Contact
- [x] EmailOctopus
- ~[ ] Emma~ couldn't test without paying
- [x] HelpScout
- [x] Trello
- [x] Twillio
- [x] Zoho

**Comment by jakejackson1** [comment]
After testing, found that the filters we need to add support for this aren't currently included in the new Settings API https://github.com/gravityforms/gravityforms/blob/develop/includes/settings/fields/class-generic-map.php#L517

Will have to wait until these filters are added back in before proceeding.

**Comment by jakejackson1** [comment]
Gravity Forms have resolved this issue. The new filter to tap into is `gform_field_map_choices`, which replaces `gform_addon_field_map_choices`.

**Comment by jakejackson1** [comment]
Upon release, notify tickets tagged with `feature-feed`

**Comment by jakejackson1** [comment]
@jestonihpi this is a key feature I want included in the next release.

**Comment by jestonihpi** [comment]
![image](https://user-images.githubusercontent.com/434866/167052972-490aa8ae-49f8-4eae-8ae1-ad13c43f362d.png)
![image](https://user-images.githubusercontent.com/434866/167052982-9d7ac996-644a-4f7f-8805-b0258c14fb70.png)
Issues found on Square Add-on.
