### ISSUE TITLE
Download Core Fonts API request limitation

### ISSUE THREAD

**Issue by debbieellis7** [GravityPDF/gravity-pdf#974]
API rate limit exceeded for https://api.github.com/repos/GravityPDF/mpdf-core-fonts/contents/

**Comment by jakejackson1** [comment]
![e2e-test-failure](https://user-images.githubusercontent.com/2918419/68368820-f07d1580-018c-11ea-80a9-2f17fb951bed.png)
@debbieellis7 the above screenshot is the reason the E2E test failed on https://travis-ci.org/GravityPDF/gravity-pdf/jobs/608594035. Do you think it is related to this issue?

**Comment by debbieellis7** [comment]
Yes @jakejackson1. I just reviewed and approved your PR.
