### ISSUE TITLE
Add option to change Nested Form layout in Core templates

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#983]
Enough people have asked, so it's worth giving users the option to show a summary table or all nested form fields. 

Working sample:

```
// Gravity PDF Nested Forms Format
class Field_Form_Original extends \GFPDF\Helper\Fields\Field_Form {
    public function html( $value = '', $label = true ) {
        add_filter( 'gpnf_template_args', function( $args ) {
            $args['template'] = 'nested-entries-detail-simple';
            return $args;
        } );
        $html = GFCommon::get_lead_field_display( $this->field, $this->get_value(), $this->entry['currency'] );
        $html = apply_filters( 'gform_entry_field_value', $html, $this->field, $this->entry, $this->form );
        return \GFPDF\Helper\Helper_Abstract_Fields::html($html);
    }
}
add_filter( 'gfpdf_field_class_form', function( $class, $field, $entry ) {
    return new Field_Form_Original( $field, $entry, GPDFAPI::get_form_class(), GPDFAPI::get_misc_class() );
}, 10, 3 );
```

**Comment by dkeys222** [comment]
Hey Jake,

David Smith from Gravity Wiz referred me to here. Thank you for your help as this is a huge help for my business.

Just have a question, is it possible to hide the headers if the field has not been filled out? I have attached a screenshot below.

[](https://prnt.sc/pe3c30)

**Comment by jakejackson1** [comment]
@dkeys222 good question. Unfortunately, no, hiding columns won't be possible by default. The idea is this layout will exactly match what the Nested Forms plugin outputs in your Entry Details page (minus the admin links).

**Comment by dkeys222** [comment]
Is there any custom code I can use to hide the columns not being used?

On Oct 2, 2019, at 6:46 PM, Jake Jackson <notifications@github.com> wrote:

﻿

@dkeys222<https://github.com/dkeys222> good question. Unfortunately, no, hiding columns won't be possible by default. The idea is this layout will exactly match what the Nested Forms plugin outputs in your Entry Details page (minus the admin links).

**Comment by jakejackson1** [comment]
@dkeys222 sure. Anything is possible with enough code. 

Here's a helpful starting point for you: https://gravitypdf.com/documentation/v5/how-to-display-the-nested-forms-table-shown-prior-to-v5-1/. What ever gets returned in the `html` method is what will be displayed in the PDF for a Nested Form.

**Comment by jakejackson1** [comment]
Will handle in Core Booster https://github.com/GravityPDF/gravity-pdf-core-booster/issues/38

**Comment by rukunpuc** [comment]
Why the summary field values are not displaying using proper alignment with header?

**Comment by rukunpuc** [comment]
Still core booster doesn't allow to change the nested form field layout.

**Comment by jakejackson1** [comment]
@rukunpuc because we don't currently have official support for the summary layout. It's on our backlog of tasks to do.

**Comment by samboy59** [comment]
Hello
My Engilsh is not good ,Sorry.
When I add this code in woody snippet
this happend:

Don't Panic

The code snippet you are trying to save produced a fatal error on line 2:
Uncaught Error: Class 'GFPDFHelperFieldsField_Form' not found in /home/subdomain/website/wp-content/plugins/insert-php/admin/metaboxes/base-options.php(846) : eval()'d code:2 Stack trace: #0 /home/frajabza/website/wp-content/plugins/insert-php/admin/metaboxes/base-options.php(846): eval() #1 /home/frajabza/website/wp-content/plugins/insert-php/admin/metaboxes/base-options.php(983): WINP_BaseOptionsMetaBox->validateCode('// Gravity PDF ...', 'php') #2 /home/frajabza/website/wp-content/plugins/insert-php/libs/factory/metaboxes/includes/form-metabox.class.php(105): WINP_BaseOptionsMetaBox->afterSavingForm(17401) #3 /home/frajabza/website/wp-content/plugins/insert-php/libs/factory/metaboxes/metabox.class.php(211): Wbcr_FactoryMetaboxes409_FormMetabox->save(17401) #4 /home/frajabza/website/wp-content/plugins/insert-php/libs/factory/metaboxes/metaboxes.php(167): Wbcr_FactoryMetaboxes409_Metabox->actionSavePost(17401) #5 /home/frajabza/website/wp-includes/class-wp-hook.php(289): Wbc

The previous version of the snippet is unchanged, and the rest of this site should be functioning normally as before.

Please use the back button in your browser to return to the previous page and try to fix the code error. If you prefer, you can close this page and discard the changes you just made. No changes will be made to this site.

How can I solve that

**Comment by jakejackson1** [comment]
I don't think you've copy and pasted the snippet properly. Please refer to https://docs.gravitypdf.com/v5/how-to-display-the-nested-forms-table-shown-prior-to-v5-1/
