### ISSUE TITLE
Georgian fonts shown as square in labels

### ISSUE THREAD

**Issue by EarendilM83** [GravityPDF/gravity-pdf#988]
Georgian fonts shown as square in labels in PDF file. Text written in input fields are shown normally as it should be but in labels there are only squares. I have installed several fonts in settings ->PDF -> tools ->manage fonts. none of them worked, tried other languages like Russian and Spanish characters and they look normally but Georgian characters doesn't. probably there is another problem i couldn't identify yet... Help please...
![2019-10-17_12h57_09](https://user-images.githubusercontent.com/26969070/66994467-5ae6ec80-f0de-11e9-8145-b9921708df69.png)

**Comment by jakejackson1** [comment]
Thanks for opening an issue. Can you provide more specific information about the problem, such as the exact text you are trying to display in the label and whether using one of the core fonts like DejaVu Sans presents the same problem?

**Comment by EarendilM83** [comment]
Hi, thanks for your replay.

I've tried dejavu sans and other core fonts. Also there is no matter what
I'm writing in labels, any text written in Georgian shown as squares.
Googling whole day but found nothing

**Comment by EarendilM83** [comment]
Here's an update. There was problem during installing I guess. I have
reinstated it and it works fine now. Thanks for your help

**Comment by jakejackson1** [comment]
@EarendilM83 awesome! Glad it was a simple fix for you.
